{{- if gt (int .Values.director.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sorry-cypress-helm.fullname" . }}-director
  labels:
    app: {{ include "sorry-cypress-helm.fullname" . }}-director
spec:
  selector:
    matchLabels:
      app: {{ include "sorry-cypress-helm.fullname" . }}-director
  minAvailable: 1
{{- end }}
