{{- if .Values.director.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.director.serviceAccount.name }}
  labels:
    app: {{ include "sorry-cypress-helm.fullname" . }}-director
  {{- with .Values.director.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
